[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "Full"
startup_mode = "Windowed"
opacity = 0.95

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "BlexMono Nerd Font Mono", style = "Regular" }
bold = { family = "BlexMono Nerd Font Mono", style = "Bold" }
italic = { family = "BlexMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "BlexMono Nerd Font Mono", style = "Bold Italic" }
size = 15.0

[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 0
y = 0

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[colors.normal]
black = "#1e2127"
red = "#e06c75"
green = "#98c379"
yellow = "#d19a66"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#abb2bf"

[colors.bright]
black = "#5c6370"
red = "#e06c75"
green = "#98c379"
yellow = "#d19a66"
blue = "#61afef"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#ffffff"

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "Insert", mods = "Shift", action = "PasteSelection" },
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
    { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
    { key = "F11", action = "ToggleFullscreen" },
]

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
command = "xdg-open"
post_processing = true
mouse.enabled = true

[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false

